### ISSUE TITLE
兄弟，再请教个问题

### ISSUE THREAD

**Issue by Lsy1992** [cjhandroid/AuthNumberView#2]
想要做个一键清空输入内容的话应该用什么方法？ 比如现在输入的验证码是错误的，然后清空后焦点回到第一个输入框让用户重新输入

**Comment by cjiahuan** [comment]
我倒是没考虑到这个问题，恩，谢谢提醒

**Comment by Lsy1992** [comment]
(⊙o⊙)…还有就是，如果我用的自定义数字键盘，不想碰到验证码输入框的时候弹出系统软键盘怎么办？
使用     android:clickable="false"
            android:focusable="false" 这两个不管用啊

**Comment by cjiahuan** [comment]
你的第一个问题解决了，resetCode，但是第二个问题，恐怕得等一两天，一时半会儿解决不了

**Comment by Lsy1992** [comment]
谢谢啊
